config/routes.rb
Rails.application.routes.draw do
  resources :markets
  resources :inventories
  resources :items
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get '/login', to: 'main#login', as: 'main_login'
  get '/main', to: 'main#main', as: 'main_main'
  get '/profile', to: 'main#profile', as: 'main_profile'
  get '/new_account', to: 'main#new_account', as: 'new_account'
  get '/new_password', to: 'main#new_password', as: 'new_password'
  get '/new_profile', to: 'main#new_profile', as: 'new_profile'
  get '/top_seller', to: 'main#top_seller', as: 'top_seller'
  get '/my_market', to: 'main#my_market' , as: 'main_my_market'
  get '/purchase_history', to: 'main#purchase_history' , as: 'main_purchase_history'
  get '/sale_history' , to: 'main#sale_history' , as: 'main_sale_history'
  get '/my_inventory', to: 'main#my_inventory', as: 'main_my_inventory'
  get '/calculate_market', to: 'main#calculate_market', as: 'cal_market'
  get '/search_category' , to: 'main#search_category', as: 'search_category'
  get '/delete_item', to: 'main#delete_item', as: 'delete_item'
  get '/edit_product', to: 'main#edit_product', as: 'edit_product'
  get '/edit', to: 'main#edit', as: 'edit'
  get '/add_product', to: 'main#add_product', as: 'add_product'
  get '/add', to: 'main#add', as: 'add'
  post '/update_password', to: 'main#update_password', as: 'update_password'
  post '/update_profile', to: 'main#update_profile', as: 'update_profile'
  post '/search_top', to: 'main#search_top', as: 'search_top'
  post '/create_user', to: 'main#create_user', as: 'create_user'
  post '/calculate_market', to: 'main#calculate_market', as: 'main_calculate_market'
  post '/search_category', to: 'main#search_category', as: 'main_search_category'
  post '/edit', to: 'main#edit'
  post '/add', to: 'main#add'
  post 'main/create'
  delete '/sign_out', to: 'main#sign_out', as: 'sign_out'
  match '*unmatched', to: 'application#not_found_method', via: :all
  # root "articles#index"
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :access_my_market, only: %i[ my_market purchase_history]
  before_action :access_by_seller, only: %i[ sale_history my_inventory top_seller]
  before_action :reset_search, only: %i[login profile main purchase_history sale_history my_inventory top_seller ]

  def login
    if is_login?
      redirect_to main_main_path
    end
  end

  def create
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password])
      session[:logged_in] = true
      session[:userId] = user.id
      session[:userEmail] = user.email
      session[:user_type] = user.user_type
      redirect_to main_main_path
    else
      redirect_to main_login_path, alert: 'Wrong username or password.' and return 
    end
  end

  def main
    if must_be_logged_in
      @user = User.where(id: session['userId']).first
    end
  end

  def profile
    if must_be_logged_in
      @a = User.where(id: session['userId']).first
    end
  end

  def new_profile
    if must_be_logged_in
      @a = User.where(id: session['userId']).first
    end
  end

  def new_password
    if must_be_logged_in
      @a = User.where(id: session['userId']).first
    end
  end

  def update_profile
    if session[:userEmail] != params[:email]
      user = User.where(email: params[:email]).first
      if user
        redirect_to new_profile_path(name: params[:name]), alert: 'This email is already used.'
      else
        user = User.where(id: session["userId"]).first
        user.update(email: params[:email], name: params[:name], user_type: params[:role].to_i, lock_version: params[:lock_version].to_i)
        session[:userEmail] = user.email
        session[:user_type] = user.user_type
        redirect_to main_profile_path, :flash => { :success => "Update your profile successfully." }
      end
    else
      user = User.where(id: session["userId"]).first
      user.update(name: params[:name], user_type: params[:role].to_i, lock_version: params[:lock_version].to_i)
      session[:user_type] = user.user_type
      redirect_to main_profile_path, :flash => { :success => "Update your profile successfully." }
    end
  end

  def update_password
    user = User.where(id: session["userId"]).first
    if user
      user.update(password: params[:newPassword], lock_version: params[:lock_version].to_i)
      redirect_to main_profile_path, :flash => { :success => "Change password successfully." }
    else
      redirect_to new_password_path, :flash => { :alert => "Cannot change your password. Please try agian." } 
    end
  end

  def new_account
  end

  def search_top
    tps = Inventory.joins("inner join users on users.id = inventories.seller_id").select("users.name, seller_id, sum(price) as total_price").where("inventories.created_at >= ? and inventories.created_at <= ?", params[:start_date], params[:end_date]).group(:seller_id).order("total_price DESC").first
    tqs = Inventory.joins("inner join users on users.id = inventories.seller_id").select("users.name, seller_id, sum(qty) as total_qty").where("inventories.created_at >= ? and inventories.created_at <= ?", params[:start_date], params[:end_date]).group(:seller_id).order("total_qty DESC").first
    if tps && tqs
      redirect_to top_seller_path(tps: {:name => tps.name, :total_price => tps.total_price}, tqs: {:name => tqs.name, :total_qty => tqs.total_qty})
    else
      redirect_to top_seller_path
    end
  end

  def top_seller
    if must_be_logged_in
      if params[:tqs] && params[:tps]
        @permitted_tqs = params.require(:tqs).permit(:name, :total_qty)
        @permitted_tps = params.require(:tps).permit(:name, :total_price)
      end
    end
  end

  def create_user
    user = User.where(email: params[:email]).first
    if user
      redirect_to new_account_path(name: params[:name]), alert: 'This email is already used.'
    else
      User.create(email: params[:email], name: params[:name], password: params[:password], user_type: params[:role].to_i)
      redirect_to main_login_path, :flash => { :success => "Your account has been created." }
    end
  end

  def sign_out
    reset_session
    redirect_to main_login_path
  end 

  #-----------------------------------------------

  def my_market
    @market = Market.all
  end

  def calculate_market
    amount = params[:amount].to_i
    id = params[:id]
    market = Market.find(id)
    if amount > market.stock
      redirect_to main_my_market_path, alert: 'Amount more than stock.'
    else
      market.stock = market.stock - amount
      if market.stock == 0
        market.destroy
      end
      market.save
      buyer_id = session[:userId]
      user_inventory = Inventory.where(user_id:buyer_id, item_id:market.item_id, price:market.price)
      Inventory.create(user_id:buyer_id, seller_id:market.user_id, price:market.price ,qty:amount ,item_id:market.item_id)
      redirect_to main_my_market_path
    end
  end

  def search_category
    item_id = []
    all_item = []
    is_all = params[:select]
    if is_all == 'all'
      all_item = Item.all
      all_item.each do |item|
        item_id.append(item.id)
      end
    else
      search = params[:category]
      item = Item.all
      item.each do |each_item|
        if each_item.category.include? search
          item_id.append(each_item.id)
        end
      end
    end
    session[:all_item] = item_id
    redirect_to main_my_market_path
  end

  def purchase_history
    u_id = session[:userId]
    @inventory = Inventory.where(user_id:u_id)
  end

  def sale_history
    u_id = session[:userId]
    @sale_history = Inventory.where(seller_id:u_id)
  end

  def my_inventory
    u_id = session[:userId]
    @inventory = Market.where(user_id:u_id)
  end

  def delete_item
    u_id = session[:userId]
    market_id = params[:market_id]
    market = Market.find(market_id)
    market.destroy
    redirect_to main_my_inventory_path, :flash => { :success => "Delete Successfully." }
  end

  def edit_product
    @item_id = params[:item_id]
    @market_id = params[:market_id]
    @item = Item.find(@item_id)
    @market = Market.find(@market_id)
  end

  def edit
    market_id = params[:market_id]
    item_id = params[:item_id]
    market = Market.find(market_id)
    item = Item.find(item_id)
    if params[:name] != "" 
      item.name = params[:name]
    end
    if params[:quantity] != "" 
      market.stock = params[:quantity].to_i
    end
    if params[:price] != "" 
      market.price = params[:price].to_f
    end
    if params[:enable] == "true" 
      item.enable = 1
    elsif params[:enable] == "false"
      item.enable = 0
    end
    if params[:image] != nil
      item.image = params[:image]
    end
    market.save
    item.save
    redirect_to main_my_inventory_path, :flash => { :success => "Edit Successfully." }
  end

  def add_product
  end

  def add
    u_id = session[:userId]
    name = params[:name]
    category = params[:category]
    price = params[:price]
    qty = params[:quantity]
    img = params[:image]
    Item.create(name:name,category:category,enable:1,image:img)
    id = Item.last.id
    Market.create(user_id:u_id,item_id:id,price:price,stock:qty)
    redirect_to main_my_inventory_path, :flash => { :success => "Create Product Successfully." }
  end

  private
    def reset_search
      session[:all_item] = nil
    end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/add_product.html.erb
<h1><i class="fa-solid fa-boxes-stacked"></i>&nbsp; Add product</h1>

<br>

<%= form_with url: add_path, data: {turbo: false} do |form| %>
    <table class="table">
        <tbody>
            <tr>
                <th scope="row">Product Name</th>
                <td><%=form.text_field :name , class: 'form-control', :required => true%></td>
            </tr>
            <tr>
                <th scope="row">Category</th>
                <td><%=form.text_field :category , class: 'form-control', :required => true%></td>
            </tr>
            <tr>
                <th scope="row">Price</th>
                <td><%=form.text_field :price , class: 'form-control', :required => true%></td>
            </tr>
            <tr>
                <th scope="row">Quantity</th>
                <td><%=form.text_field :quantity , class: 'form-control', :required => true%></td>
            </tr>
            <tr>
                <th scope="row">Image</th>
                <td><%= form.file_field :image %></td>
            </tr>
        </tbody>
    </table>
    <%=form.submit :Create , class: 'btn btn-primary'%>
<%end%>

app/views/main/calculate_market.html.erb
<h1>Main#calculate_market</h1>

app/views/main/edit_product.html.erb
<style>
    .image {
        max-width: 300px;
        max-height: 15ss0px;
    }
</style>

<h1><i class="fa-solid fa-pen"></i>&nbsp; Edit product</h1>
<br>

<%= form_with url: edit_path, data: {turbo: false} do |form| %>
    <%= hidden_field_tag 'item_id', @item_id  %>
    <%= hidden_field_tag 'market_id', @market_id  %>

    <%= hidden_field_tag :lock_version_items, @item_id  %>
    <%= hidden_field_tag :lock_version_markets, @item_id  %>

    <table class="table">
        <thead>
         <tr class = "table-secondary">
            <th scope="col">Data</th>
            <th scope="col">Old Data</th>
            <th scope="col">Edit Data</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">Product Name</th>
                <td><%= @item.name %></td>
                <td><%=form.text_field :name , class: 'form-control'%></td>
            </tr>
            <tr>
                <th scope="row">Price</th>
                <td><%= @market.price %></td>
                <td><%=form.text_field :price , class: 'form-control'%></td>
            </tr>
            <tr>
                <th scope="row">Quantity</th>
                <td><%= @market.stock %></td>
                <td><%=form.text_field :quantity , class: 'form-control'%></td>
            </tr>
             <tr>
                <th scope="row">Enable Product</th>
                <% if @item.enable == 1 %>
                    <td>Enable</td>
                <% else %>
                    <td>Disable</td>
                <% end %>
                <td><%= form.radio_button :enable, "true" %>
                <%= form.label :enable_item, "Enable" %>
                <%= form.radio_button :enable, "false" %>
                <%= form.label :disable_item, "Disable" %></td>
            </tr>
            <tr>
                <th scope="row">Edit Picture</th>
                <td><%= image_tag @item.image_url, :class => "image" if @item.image %></td>
                <td><%= form.file_field :image %></td>
            </tr>
        </tbody>
    </table>
    <%=form.submit :Edit , class: 'btn btn-primary'%>
<%end%>

app/views/main/login.html.erb
<h1>Main#login</h1>
<p>Find me in app/views/main/login.html.erb</p>

app/views/main/my_inventory.html.erb
<h1><i class="fa-solid fa-box-archive"></i>&nbsp; My inventory</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @inventory.each do |product| %>
    <% item = Item.where(id:product.item_id).first%>
    <% item_name = item.name%>
        <tr>
            <td><%= item_name %></td>
            <td><%= product.price %></td>
            <td><%= product.stock %></td>
            <% if item.enable == 1 %>
                <td>Enable</td>
            <% else %>
                <td>Disable</td>
            <%end%>
            <td><%= link_to "Edit Product", edit_product_path(item_id:item.id, market_id:product.id) , class: 'btn btn-success'%></td>
            <td><%= link_to "Destroy this product", delete_item_path(item_id:item.id, market_id:product.id), class: 'btn btn-danger' %></td>
        </tr>
    <%end%>
  </tbody>
</table>

<% if @inventory == [] %>
<div class="text-center">
    No data
</div>
<% end %>

<%= link_to "Add New Product", add_product_path , class: 'btn btn-success'%>

app/views/main/my_market.html.erb
<style>
    .image {
        max-width: 300px;
        max-height: 150px;
    }
</style>

<h1><i class="fa-solid fa-shop"></i>&nbsp; My market</h1>
<br>

<div class="container text-center">
    <div class="row">
        <div class="col"><h5>Search by Category</h5></div>
        <div class="col">
            <%= form_with url: search_category_path, data: {turbo: false} do |form| %>
                <div class="input-group mb-3">
                    <%=form.text_field :category , class: 'form-control' %>
                    <%=form.submit :Search , class: 'btn btn-outline-success'%>
                </div>
            <%end%>
        </div>
        <div class="col"><%= link_to "Show All", search_category_path(select: 'all') , class: 'btn btn-outline-primary'%></div>
    <div>
</div>
    

<table class="table table-striped">
<thead>
    <tr>
    <th scope="col">Seller</th>
    <th scope="col">Item</th>
    <th scope="col">Price</th>
    <th scope="col">Stock</th>
    <th scope="col">Amount</th>
    <th scope="col">Picture</th>
    </tr>
</thead>
<tbody>
    <% if session[:all_item].nil? %>
        <% @market.each do |market| %>
            <% user = User.where(id:market.user_id).first %>
            <% user_name = user.name %>
            <% item = Item.where(id:market.item_id).first %>
            <% item_name = item.name %>
            <% if item.enable == 1 %>
                <tr>
                    <th scope='col'><%= user_name %></th> 
                    <th scope='col'><%= item_name %></th> 
                    <th scope='col'><%= market.price %></th> 
                    <th scope='col'><%= market.stock %></th> 
                    <th scope='col'>
                        <%= form_with url: cal_market_path, data: {turbo: false} do |form| %>
                        <div class="input-group mb-3">
                            <%= hidden_field_tag 'id', market.id  %>
                            <%= hidden_field_tag 'item_id', market.item_id  %>
                            <%= hidden_field_tag 'seller_id', market.user_id  %>
                            <%=form.text_field :amount , class: 'form-control'%>
                            <%=form.submit :Buy , class: 'btn btn-primary'%>
                        </div>
                        <%end%>
                    </th>
                    <th><%= image_tag item.image_url, :class => "image" if item.image %></th>
                </tr>
            <%end%>
        <%end%>
    <% else %>
        <% item_id = session[:all_item]%>
        <% item_id.each do |item| %>
            <% market_item = Market.where(item_id:item) %>
            <% market_item.each do |market| %>
                <% user = User.where(id:market.user_id).first %>
                <% user_name = user.name %>
                <% item = Item.where(id:market.item_id).first %>
                <% item_name = item.name %>
                <% if item.enable == 1 %>
                    <tr>
                        <th scope='col'><%= user_name %></th> 
                        <th scope='col'><%= item_name %></th> 
                        <th scope='col'><%= market.price %></th> 
                        <th scope='col'><%= market.stock %></th> 
                        <th scope='col'>
                            <%= form_with url: cal_market_path, data: {turbo: false} do |form| %>
                            <div class="input-group mb-3">
                                <%= hidden_field_tag 'id', market.id  %>
                                <%= hidden_field_tag 'item_id', market.item_id  %>
                                <%= hidden_field_tag 'seller_id', market.user_id  %>
                                <%=form.text_field :amount , class: 'form-control'%>
                                <%=form.submit :Buy , class: 'btn btn-primary'%>
                            </div>
                            <%end%>
                        </th>
                        <th><%= image_tag item.image_url, :class => "image" if item.image %></th>
                    </tr>
                <%end%>
            <%end%>
        <%end%>
    <%end%>
</tbody>
</table>

<% if !@market && session[:all_item] == nil || session[:all_item] == [] %>
<div class="text-center">
    No data
</div>
<% end %>

app/views/main/new_account.html.erb
<%= form_with url: create_user_path, method: :post, data: {turbo: false} do |form| %>
    <h1 style="margin-bottom: 20px;"><i class="fa-solid fa-circle-user"></i> Create a new account</h1>
    <label for="email" class="form-label"><b>Email</b>: </label>
    <input type="text" class="form-control form" name="email" id="email">
    <div class="invalid-feedback" id="email-feedback"></div>
    <label for="name" class="form-label" style="margin-top:10px;"><b>Name</b>:</label>
    <input type="text" class="form-control form" name="name" id="name" value="<%= @name %>">
    <div class="invalid-feedback" id="name-feedback"></div>
    <label for="password" class="form-label" style="margin-top:10px;"><b>Password</b>:</label>
    <input type="password" class="form-control form" name="password" id="password">
    <div class="invalid-feedback" id="password-feedback"></div>
    <label for="re_password" class="form-label" style="margin-top:10px;"><b>Re-password</b>:</label>
    <input type="password" class="form-control form" name="re_password" id="re-password">
    <div class="invalid-feedback" id="re-password-feedback"></div>
    <label for="user_type" class="form-label" style="margin-top:10px;"><b>Role</b>:</label>
    <select name="role" id="role" class="form-select form" aria-label="role">
        <option value="" selected>Select your role</option>
        <option value="1">Seller</option>
        <option value="2">Buyer</option>
    </select>
    <div class="invalid-feedback" id="role-feedback"></div>
    <button id="create" type="button" class="btn btn-primary mt-3">Create</button>
<% end %>    

<%= javascript_pack_tag 'new_account' %>

app/views/main/new_password.html.erb
<h1><i class="fa-solid fa-key"></i>&nbsp; New password</h1>
<%= form_with url: update_password_path, method: :post, data: {turbo: false}, id: :form do |form| %>
<%= form.hidden_field :lock_version, :value => @a.lock_version %>
<label for="newPassword" class="form-label">New password: </label>
<input type="password" class="form-control form" name="newPassword" id="newPassword" required>
<div class="invalid-feedback" id="newPassword-feedback"></div>
<label for="newPassword2" class="form-label mt-2">Re-enter new password:</label>
<input type="password" class="form-control form" name="re_password" id="re-password" required>
<div class="invalid-feedback" id="re-password-feedback"></div>
<button id="confirm" type="button" class="btn btn-primary mt-3">Confirm</button>
<% end %>   

<%= javascript_pack_tag 'new_password' %>

app/views/main/new_profile.html.erb
<h1><i class="fa-solid fa-address-card"></i>&nbsp; New Profile</h1>
<%= form_with url: update_profile_path, method: :post, data: {turbo: false}, id: :form do |form| %>
<%= form.hidden_field :lock_version, :value => @a.lock_version %>
<label for="email" class="form-label"><b>New email</b>: </label>
<input type="text" class="form-control form" name="email" id="email" placeholder="Enter your new email" required>
<div class="invalid-feedback" id="email-feedback"></div>
<label for="name" class="form-label mt-2"><b>New name</b>:</label>
<input type="text" class="form-control form" name="name" id="name" placeholder="Enter your new name" required>
<div class="invalid-feedback" id="name-feedback"></div>
<label for="role" class="form-label" style="margin-top:10px;"><b>Role</b>:</label>
    <select name="role" id="role" class="form-select form" aria-label="role">
        <option value="" selected>Select your role</option>
        <option value="1">Seller</option>
        <option value="2">Buyer</option>
    </select>
    <div class="invalid-feedback" id="role-feedback"></div>
<button id="update" type="button" class="btn btn-primary mt-3">Update</button>
<% end %>   

<%= javascript_pack_tag 'new_profile' %>

app/views/main/profile.html.erb
<h1>Main#profile</h1>
<p>Find me in app/views/main/profile.html.erb</p>

app/views/main/purchase_history.html.erb
<h1><i class="fa-solid fa-basket-shopping"></i>&nbsp; Purchase history</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">From</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Purchase time</th>
    </tr>
  </thead>
  <tbody>
    <% @inventory.each do |product| %>
    <% item = Item.where(id:product.item_id).first%>
    <% item_name = item.name%>
    <% seller = User.where(id:product.seller_id).first %>
    <% seller_name = seller.name %>
        <tr>
            <td><%= item_name %></td>
            <td><%= seller_name %></td>
            <td><%= product.price %></td>
            <td><%= product.qty %></td>
            <td><%= product.created_at%></td>
        </tr>
    <%end%>
  </tbody>
</table>

<% if @inventory == [] || !@inventory %>
<div class="text-center">
    No data
</div>
<% end %>

app/views/main/sale_history.html.erb
<h1><i class="fa-solid fa-right-left"></i>&nbsp; Sale history</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">To</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      <th scope="col">Sale time</th>
    </tr>
  </thead>
  <tbody>
    <% @sale_history.each do |product| %>
    <% item = Item.where(id:product.item_id).first%>
    <% item_name = item.name%>
    <% buyer = User.where(id:product.user_id).first %>
    <% buyer_name = buyer.name %>
        <tr>
            <td><%= item_name %></td>
            <td><%= buyer_name %></td>
            <td><%= product.price %></td>
            <td><%= product.qty %></td>
            <td><%= product.created_at%></td>
        </tr>
    <%end%>
  </tbody>
</table>

<% if @sale_history == [] %>
<div class="text-center">
    No data
</div>
<% end %>

app/views/main/search_category.html.erb
<h1>main#search_category</h1>

app/views/main/top_seller.html.erb
<h1><i class="fa-solid fa-user"></i>&nbsp; Top seller</h1>
<%= form_with url: search_top_path, method: :post, data: {turbo: false}, id: :form do |form| %>
<div class="search-box mt-3 row">
    <div class="col-12 col-md-5">
        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">Start date:</span>
            <input id="start_date" name="start_date" type="date" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            <div class="invalid-feedback" id="start_date-feedback"></div>
        </div>
    </div>
    <div class="col-12 col-md-5">
        <div class="input-group mb-3">
            <span class="input-group-text" id="inputGroup-sizing-default">End date:</span>
            <input id="end_date" name="end_date" type="date" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            <div class="invalid-feedback" id="end_date-feedback"></div>
        </div>
    </div>
    <div class="col-6 col-md-2">
        <button id="search" type="button" class="btn btn-outline-success"><i class="fa-solid fa-magnifying-glass"></i> Search</button>
    </div>
</div>
<% end %>

<table class="table caption-top">
  <caption>Top price seller</caption>
  <thead>
    <tr>
      <th class="col-2" scope="col">#</th>
      <th class="col-5" scope="col">Name</th>
      <th class="col-5" scope="col">Price</th>
    </tr>
  </thead>
  <% if @permitted_tps %>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= @permitted_tps['name'] %></td>
      <td><%= @permitted_tps['total_price'] %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<% if !@permitted_tps %>
    <div class="text-center">
        No data
    </div>
<% end %>

<table class="table caption-top">
  <caption>Top quantity seller</caption>
  <thead>
    <tr>
      <th class="col-2" scope="col">#</th>
      <th class="col-5" scope="col">Name</th>
      <th class="col-5" scope="col">Quantity</th>
    </tr>
  </thead>
  <% if @permitted_tqs %>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= @permitted_tqs['name'] %></td>
      <td><%= @permitted_tqs['total_qty'] %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<% if !@permitted_tqs %>
    <div class="text-center">
        No data
    </div>
<% end %>

<%= javascript_pack_tag 'top_seller' %>